/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include<stdio.h>

extern void initialise_monitor_handles(void);// this is the prototype

int main(void)
{
	int b=0,i;
	initialise_monitor_handles(); // before using any printf statement call this function

	for(;;)
	{
		printf("Hello World\n");
		b++;
		for(i=0;i<10000;i++);
	}
}
